apiVersion: apps/v1
kind: Deployment
metadata:
  name: libraryapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libraryapp
  template:
    metadata:
      labels:
        app: libraryapp
    spec:
      containers:
      - name: app
        image: sqlnet6apik8s:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
