apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtool
  labels:
    name: library-ingress
spec:
  rules:
  - host: libraryapp-deployment.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: library-servicenp
            port: 
              number: 80